// This file is generated by kconfig_compiler from datappconfig.kcfg.
// All changes you do to this file will be lost.

#include "datappconfig.h"
#include "settings_config.h"

using namespace Nepomuk;

DataPPConfig::DataPPConfig(  KSharedConfig::Ptr config  )
  : DataPPConfigBase( config )
{
}

DataPPConfig::DataPPConfig(  const QString & name  )
  : DataPPConfigBase( KSharedConfig::openConfig(path.arg(name) ) )
{
}

KSharedConfigPtr DataPPConfig::config(  const QString & name  )
{
    return KSharedConfig::openConfig(path.arg(name));
}

DataPPConfig::~DataPPConfig()
{
}

QString Nepomuk::DataPPConfig::path = QString(PLUGIN_CONFIG_DIR"%1rc");
